# Generated by Django 2.1 on 2019-04-06 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
    ]
